annotation_path: train_pti01_6342imgs_v20180706193526_keras.txt
log_dir: logs/default-tiny-scratch-000/
classes_path: model_data/pti_classes.txt
anchors_path: model_data/tiny_yolo_anchors.txt
model_name: default_tiny_yolo
