dataset_name: pti01
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt_new-ratio_round-type-up_side-ajustment-one.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt_new-ratio_round-type-up_side-ajustment-one.txt
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
train_path: train_pti01_v20180925220014_keras.txt
test_path: test_pti01_v20180925220014_keras.txt
classes_path: model_data/pti_classes.txt
anchors_path: model_data/tiny_yolo_anchors.txt
# anchors_path: model_data/pti_tiny_640x480_anchors.txt
# anchors_path: model_data/pti_tiny_416x416_anchors.txt
model_name: tiny_yolo
pretrained_weights_path: model_data/yolov3-tiny.h5
log_dir: logs/default-tiny-013
epochs_freezed: 0
batch_size_freezed: 2
epochs_unfreezed: 100
batch_size_unfreezed: 2
short_comment: lr0.0001_640x480net
