dataset_name: pti01
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt
train_path: train_pti01_6342imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
test_path: test_pti01_1585imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
classes_path: model_data/pti_classes.txt
anchors_path: model_data/yolo_anchors.txt
model_name: yolo
pretrained_weights_path: model_data/yolov3.h5
log_dir: logs/default-001/
batch_size_freezed: 2
epochs_freezed: 10
batch_size_unfreezed: 2
epochs_unfreezed: 100
short_comment: lr0.0001_640x480net
