#WHY DID I PREPARE THIS?

# dataset_name: caltech
# train_path: train_shanshan_1x_keras.txt
# test_path: test_shanshan_1x_keras.txt
# classes_path: model_data/caltech_classes.txt
# model_name: yolo_infusion
# seg_loss_weight: 2
# pretrained_weights_path: model_data/yolov3.h5
# log_dir: logs/caltech_yolov3-seg-010
# anchors_path: model_data/yolo_anchors_k3.txt
# # anchors_path: model_data/yolo_anchors.txt
# input_width: 640
# input_height: 480
# epochs_freezed: 0
# batch_size_freezed: 2
# epochs_unfreezed: 100
# batch_size_unfreezed: 8
# data_augmentation: full
# short_comment: shanshan_infusion_full
