dataset_name: pti01
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt
# train_path: train_pti01_6342imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
# test_path: test_pti01_1585imgs_v20180706193526_keras.txt_new-ratio_round-type-normal_side-ajustment-one.txt
train_path: train_pti01_v20180925220014_keras.txt
# test_path: train_pti01_v20180925220014_keras.txt
test_path: test_pti01_v20180925220014_keras.txt
classes_path: model_data/pti_classes.txt
# anchors_path: model_data/yolo_anchors.txt
anchors_path: model_data/yolo_anchors_k3.txt
model_name: yolo
input_width: 1280
input_height: 960
pretrained_weights_path: model_data/yolov3.h5
data_augmentation: False
log_dir: logs/default-015
initial_lr: 0.00001 #10^-5
batch_size_freezed: 2
epochs_freezed: 1
batch_size_unfreezed: 2
epochs_unfreezed: 100
#same as 007 but changing LR to 10^-5
short_comment: higher-inputs_lower-lr
