train_path: train_pti01_6342imgs_v20180706193526_keras.txt
test_path: test_pti01_1585imgs_v20180706193526_keras.txt
classes_path: model_data/pti_classes.txt
anchors_path: model_data/tiny_yolo_anchors.txt
model_name: tiny_yolo_infusion
log_dir: logs/seg-004/
