dataset_name: caltech
train_path: train_caltech10x_42782imgs_v20181024211330_keras.txt
test_path: test_caltech_4024imgs_v20181024211330_keras.txt
classes_path: model_data/caltech_classes.txt
anchors_path: model_data/yolo_caltech10x_anchors_k2.txt
model_name: tiny_yolo_infusion
pretrained_weights_path: model_data/yolov3-tiny.h5
log_dir: logs/caltech_seg-020
seg_loss_weight: 4
input_width: 640
input_height: 480
epochs_freezed: 0
batch_size_freezed: 2
epochs_unfreezed: 15
batch_size_unfreezed: 2
data_augmentation: flip_only
short_comment: final_experiments_1
