dataset_name: caltech
train_path: train_shanshan_1x_keras.txt
test_path: test_shanshan_1x_keras.txt
classes_path: model_data/caltech_classes.txt
# anchors_path: model_data/tiny_yolo_anchors.txt
anchors_path: model_data/yolo_anchors_k2.txt
model_name: tiny_yolo_infusion
pretrained_weights_path: model_data/yolov3-tiny.h5
log_dir: logs/caltech_seg-010
seg_loss_weight: 8
input_width: 640
input_height: 480
epochs_freezed: 0
batch_size_freezed: 2
epochs_unfreezed: 100
batch_size_unfreezed: 2
data_augmentation: flip_only
short_comment: comparing_seg_loss_weights
