dataset_name: caltech
train_path: train_caltech10x_42782imgs_v20181024211330_keras.txt
test_path: test_caltech_4024imgs_v20181024211330_keras.txt
classes_path: model_data/caltech_classes.txt
model_name: yolo_infusion
seg_loss_weight: 2
# pretrained_weights_path: model_data/yolov3.h5
pretrained_weights_path: logs_caltech_yolov3-001_ep001-loss40.297-val_loss17.006.h5
log_dir: logs/caltech_yolov3-seg-005
anchors_path: model_data/yolo_anchors_k3.txt
# anchors_path: model_data/yolo_anchors.txt
input_width: 640
input_height: 480
epochs_freezed: 0
batch_size_freezed: 2
epochs_unfreezed: 100
batch_size_unfreezed: 2
data_augmentation: full
short_comment: yolov3-infusion_retrained_full
