dataset_name: pti01
train_path: train_pti01_v20181030213454_by_event_keras.txt
test_path: test_pti01_v20181030213454_by_event_keras.txt
classes_path: model_data/pti_8_classes.txt
class_translation_path: pti01_class_translation_one-class_004.yml
anchors_path: model_data/yolo_anchors_k2.txt
model_name: tiny_yolo
input_width: 640
input_height: 480
pretrained_weights_path: model_data/yolov3-tiny.h5
log_dir: logs/default-tiny-063
epochs_freezed: 1
batch_size_freezed: 2
epochs_unfreezed: 100
batch_size_unfreezed: 2
data_augmentation: flip_only
short_comment: trying-baseline-1
