dataset_name: pti01
train_path: train_pti01_v20181018205401_keras.txt
test_path: test_pti01_v20181018205401_keras.txt
classes_path: model_data/pti_8_classes.txt
anchors_path: model_data/yolo_anchors_k3.txt
model_name: yolo_infusion
seg_loss_weight: 2
input_width: 640
input_height: 480
# pretrained_weights_path: model_data/yolov3.h5
pretrained_weights_path: logs_caltech_yolov3-001_ep001-loss40.297-val_loss17.006.h5
data_augmentation: flip_only
log_dir: logs/default-seg-008
batch_size_freezed: 2
epochs_freezed: 1
batch_size_unfreezed: 2
epochs_unfreezed: 100
short_comment: pretrained-on-caltech
