dataset_name: pti01
train_path: train_pti01_6342imgs_v20180706193526_keras.txt
test_path: test_pti01_1585imgs_v20180706193526_keras.txt
classes_path: model_data/pti_classes.txt
anchors_path: model_data/yolo_anchors.txt
model_name: yolo_small_objs
pretrained_weights_path: model_data/yolov3.h5
log_dir: logs/default-small-objs-000/
short_comment: batch4-10freezed_lr0.0001_640x480net
