dataset_name: pti01
train_path: train_pti01_v20181030213454_by_event_keras.txt
test_path: test_pti01_v20181030213454_by_event_keras.txt
classes_path: model_data/pti_8_classes.txt
anchors_path: model_data/yolo_anchors_k3.txt
model_name: yolo
input_width: 640
input_height: 480
pretrained_weights_path: model_data/yolov3.h5
data_augmentation: full
log_dir: logs/default-034
batch_size_freezed: 2
epochs_freezed: 1
batch_size_unfreezed: 2
epochs_unfreezed: 100
short_comment: dataset_by_event_full_data_aug
