dataset_name: pti01
train_path: train_pti01_6342imgs_v20180706193526_keras.txt
test_path: test_pti01_1585imgs_v20180706193526_keras.txt
classes_path: model_data/pti_classes.txt
anchors_path: model_data/yolo_anchors_k3.txt
model_name: yolo
input_width: 640
input_height: 480
pretrained_weights_path: model_data/yolov3.h5
data_augmentation: flip_only
log_dir: logs/default-030
batch_size_freezed: 2
epochs_freezed: 1
batch_size_unfreezed: 2
epochs_unfreezed: 100
short_comment: testing_pti01_v1
